export default {
  compilerOptions: {
    jsx: 'preserve',
    jsxFactory: 'h',
    moduleResolution: 'node',
    esModuleInterop: true,
    skipLibCheck: true,
    forceConsistentCasingInFileNames: true,
    strict: true,
    target: 'esnext',
    module: 'esnext',
    lib: ['esnext', 'dom'],
    baseUrl: '.',
    paths: {
      '@/*': ['src/*'],
      '@utils/*': ['src/utils/*'],
      '@hooks/*': ['src/hooks/*'],
      '@pages/*': ['src/pages/*'],
      '@components/*': ['src/components/*'],
      '@types/*': ['src/types/*'],
    },
    types: ['vite/client', 'vite-plugin-md', 'node'],
  },
  include: ['vite-env.d.ts', 'src/**/*.ts', 'src/**/*.tsx', 'src/**/*.vue'],
  exclude: ['node_modules'],
};
